# Generated by Django 5.2.3 on 2025-07-22 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 22, 17, 46, 8, 983490, tzinfo=datetime.timezone.utc)),
        ),
    ]
