# Generated by Django 5.2.3 on 2025-07-22 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0004_remove_client_company_client_department_client_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='floor',
            field=models.IntegerField(choices=[(6, 'Floor Not Selected'), (0, 'Ground Floor'), (1, '1st Floor'), (2, '2nd Floor'), (3, '3rd Floor'), (4, '4th Floor'), (5, '5th Floor')], default=6),
        ),
    ]
