# Generated by Django 5.2.3 on 2025-07-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0005_alter_client_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('closed', 'Closed')], default='pending', max_length=10),
        ),
    ]
