# Generated by Django 5.2.4 on 2025-07-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0007_ticket_email_ticket_phone_number_alter_client_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='client_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
