# Generated by Django 5.2.4 on 2025-07-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0008_client_client_username_ticket_client_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Helper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('helper_username', models.CharField(max_length=255)),
                ('helper_fname', models.CharField(max_length=255)),
                ('helper_lname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
