# Generated by Django 5.2.4 on 2025-07-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0010_ticket_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='assigned_to',
        ),
        migrations.AlterField(
            model_name='helper',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='helper',
            name='helper_fname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='helper',
            name='helper_lname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
