# Generated by Django 5.2.4 on 2025-07-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0012_ticket_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_updates',
            field=models.TextField(blank=True, null=True),
        ),
    ]
