# Generated by Django 5.2.4 on 2025-07-28 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0014_alter_ticket_assigned_to'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Helper',
        ),
    ]
