# Generated by Django 5.2.4 on 2025-07-28 18:11

import django.db.models.deletion
import ticketing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0016_ticket_category_remove_ticket_ticketcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_category',
            field=models.ForeignKey(default=ticketing.models.get_default_ticket_category, on_delete=django.db.models.deletion.PROTECT, to='ticketing.ticket_category'),
        ),
    ]
