# Generated by Django 5.2.4 on 2025-07-28 10:54

import django.db.models.deletion
import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.ForeignKey(default=inventory.models.get_default_item_type, on_delete=django.db.models.deletion.PROTECT, to='inventory.item_type'),
        ),
    ]
